name: "Publish"

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Home Assistant builder
        uses: home-assistant/builder@2024.08.2
        with:
          args: |
            --repository https://github.com/bigmoby/addon-wireguard-client \
            --target wireguard_client \
            --branch main \
            --image wireguard_client \
            --all \
            --docker-hub bigmoby \
            --docker-user ${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password ${{ secrets.DOCKERHUB_TOKEN }} 
