name: "Test"

on: [workflow_dispatch]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Test build
        uses: home-assistant/builder@2024.08.2
        with:
          args: |
            --test \
            --all \
            --target wireguard_client \
            --docker-hub bigmoby
